// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCluster(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddCluster'](arg1, arg2, arg3);
}

export function AddResourceWatcher(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddResourceWatcher'](arg1, arg2, arg3, arg4, arg5);
}

export function GetClusters() {
  return window['go']['main']['App']['GetClusters']();
}

export function GetKubeconfigFiles() {
  return window['go']['main']['App']['GetKubeconfigFiles']();
}

export function GetResourceTypes(arg1) {
  return window['go']['main']['App']['GetResourceTypes'](arg1);
}

export function GetSchedulerSnapshot(arg1) {
  return window['go']['main']['App']['GetSchedulerSnapshot'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoadKubeconfigFromFile(arg1) {
  return window['go']['main']['App']['LoadKubeconfigFromFile'](arg1);
}

export function RemoveCluster(arg1) {
  return window['go']['main']['App']['RemoveCluster'](arg1);
}

export function RemoveResourceWatcher(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RemoveResourceWatcher'](arg1, arg2, arg3, arg4);
}

export function SaveKubeconfigToFile(arg1, arg2) {
  return window['go']['main']['App']['SaveKubeconfigToFile'](arg1, arg2);
}

export function Shutdown() {
  return window['go']['main']['App']['Shutdown']();
}

export function StartSchedulerAggregation(arg1) {
  return window['go']['main']['App']['StartSchedulerAggregation'](arg1);
}

export function StopSchedulerAggregation(arg1) {
  return window['go']['main']['App']['StopSchedulerAggregation'](arg1);
}

export function ToggleClusterPin(arg1) {
  return window['go']['main']['App']['ToggleClusterPin'](arg1);
}

export function WatchDefaultKubeconfig() {
  return window['go']['main']['App']['WatchDefaultKubeconfig']();
}
