// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';
import {schema} from '../models';
import {scheduler} from '../models';

export function AddCluster(arg1:string,arg2:string,arg3:string):Promise<string>;

export function AddResourceWatcher(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function GetClusters():Promise<Record<string, service.ClusterInfo>>;

export function GetKubeconfigFiles():Promise<Array<string>>;

export function GetNodes(arg1:string):Promise<Array<Record<string, any>>>;

export function GetPods(arg1:string,arg2:string):Promise<Array<Record<string, any>>>;

export function GetResourceTypes(arg1:string):Promise<Array<schema.GroupVersionResource>>;

export function GetSchedulerSnapshot(arg1:string):Promise<scheduler.SchedulerSnapshot>;

export function Greet(arg1:string):Promise<string>;

export function LoadDefaultKubeconfig():Promise<string>;

export function LoadKubeconfigFromFile(arg1:string):Promise<string>;

export function RemoveCluster(arg1:string):Promise<void>;

export function RemoveResourceWatcher(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SaveKubeconfigToFile(arg1:string,arg2:string):Promise<string>;

export function Shutdown():Promise<void>;

export function StartSchedulerAggregation(arg1:scheduler.SchedulerAggregationRequest):Promise<void>;

export function StopSchedulerAggregation(arg1:string):Promise<void>;

export function ToggleClusterPin(arg1:string):Promise<void>;

export function WatchDefaultKubeconfig():Promise<void>;
